apiVersion: v1
kind: Secret
metadata:
  name: messagesdb
  labels:
    app.kubernetes.io/component: messagesdb 
    {{- include "messages.labels" . | nindent 4 }}
type: Opaque
data:
  mongodb-root-password: "snapmsg"
  mongodb-password: "snapmsg"
