apiVersion: v1
kind: Service
metadata:
  name: messagesdb 
  labels:
    {{- include "movies.labels" . | nindent 4 }}
    app.kubernetes.io/component: messagesdb 
spec:
  type: ClusterIP
  ports:
  - name: messagesdb 
    port: 27017
    targetPort: messagesdb 
  selector:
    app.kubernetes.io/name: messagesdb 
    app.kubernetes.io/instance: {{ .Release.Name }}
